2018-11-17 13:37:25,738 - run_test.py [line:39] - INFO:list : ['2018-11-15_21-04-38UITest.html', '2018-11-15_21-07-11UITest.html', '2018-11-15_21-10-32UITest.html', '2018-11-17_13-37-15UITest.html']
2018-11-17 13:37:25,748 - run_test.py [line:48] - INFO:new reports_path:2018-11-17_13-37-15UITest.html
2018-11-17 13:37:25,752 - run_test.py [line:58] - INFO:del report : ['2018-11-15_21-04-38UITest.html']
2018-11-17 13:37:34,429 - email.py [line:127] - ERROR:用户名密码验证失败！(550, b'User has no permission')
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-packages\SelenPyTest\pyselenium\models\email.py", line 123, in send
    self._login(self.pwd)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-packages\SelenPyTest\pyselenium\models\email.py", line 107, in _login
    self.smtp.login(self.usr, pwd)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\smtplib.py", line 730, in login
    raise last_exception
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\smtplib.py", line 721, in login
    initial_response_ok=initial_response_ok)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\smtplib.py", line 642, in auth
    raise SMTPAuthenticationError(code, resp)
smtplib.SMTPAuthenticationError: (550, b'User has no permission')
2018-11-17 13:37:34,465 - email.py [line:134] - INFO:邮件发送给 ['a670662282@163.com']
